# Generated by Django 3.0.8 on 2020-08-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200804_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=1),
        ),
        migrations.AlterField(
            model_name='auction',
            name='cat',
            field=models.IntegerField(choices=[(1, 'None'), (2, 'Surrealism'), (3, 'Pop Art'), (4, 'Minimalism'), (5, 'Street Art')], default=1),
        ),
        migrations.AlterField(
            model_name='auction',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
