# Generated by Django 3.0.8 on 2020-08-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200808_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_winner',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
